// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lqpiickowwmstqdmdmjc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxxcGlpY2tvd3dtc3RxZG1kbWpjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg4MDAxOTcsImV4cCI6MjA3NDM3NjE5N30.CTXJGu3tCQdGBPxOxOccSbyuLVo3pEU0wGQkOAG2yS8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});